// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc199.OffseasonBot2016;

import org.usfirst.frc199.OffseasonBot2016.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc199.OffseasonBot2016.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    public JoystickButton shiftHighButton;
    public JoystickButton intakeButton;
    public Joystick leftJoy;
    public JoystickButton shiftLowButton;
    public JoystickButton shootButton;
    public JoystickButton mainTiltButton;
    public Joystick rightJoy;
    public JoystickButton runShooterButton;
    public JoystickButton loadShooterButton;
    public JoystickButton shootLowButton;
    public JoystickButton pivotIntakeButton;
    public JoystickButton intakeInButton;
    public JoystickButton intakeOutButton;
    public JoystickButton visionAlignButton;
    public Joystick manipulator;


    public OI() {

        manipulator = new Joystick(2);
        
        visionAlignButton = new JoystickButton(manipulator, 3);
        visionAlignButton.whenPressed(new VisionAlign());
        intakeOutButton = new JoystickButton(manipulator, 8);
        intakeOutButton.whileHeld(new RunIntakeOut());
        intakeInButton = new JoystickButton(manipulator, 6);
        intakeInButton.whileHeld(new RunIntakeIn());
        pivotIntakeButton = new JoystickButton(manipulator, 4);
        pivotIntakeButton.whenPressed(new PivotIntake());
        shootLowButton = new JoystickButton(manipulator, 2);
        shootLowButton.whileHeld(new ShootLow());
        loadShooterButton = new JoystickButton(manipulator, 5);
        loadShooterButton.whileHeld(new LoadShooter());
        runShooterButton = new JoystickButton(manipulator, 7);
        runShooterButton.whileHeld(new RunShooter());
        rightJoy = new Joystick(1);
        
        mainTiltButton = new JoystickButton(rightJoy, 2);
        mainTiltButton.whenPressed(new ToggleShootingTilt());
        shootButton = new JoystickButton(rightJoy, 5);
        shootButton.whenPressed(new AutoShoot());
        shiftLowButton = new JoystickButton(rightJoy, 3);
        shiftLowButton.whenPressed(new ShiftGearsLow());
        leftJoy = new Joystick(0);
        
        intakeButton = new JoystickButton(leftJoy, 5);
        intakeButton.whenPressed(new AutoIntake());
        shiftHighButton = new JoystickButton(leftJoy, 3);
        shiftHighButton.whenPressed(new ShiftGearsHigh());


        // SmartDashboard Buttons
        SmartDashboard.putData("ShiftGearsLow", new ShiftGearsLow());
        SmartDashboard.putData("ShiftGearsHigh", new ShiftGearsHigh());
        SmartDashboard.putData("MainAutoMode", new MainAutoMode());
        SmartDashboard.putData("AutoDrive", new AutoDrive(0));
        SmartDashboard.putData("AutoTurn", new AutoTurn(0));
        SmartDashboard.putData("AutoDelay", new AutoDelay(0));
        SmartDashboard.putData("TeleopDrive", new TeleopDrive());
        SmartDashboard.putData("VisionAlign", new VisionAlign());
        SmartDashboard.putData("AutoShoot", new AutoShoot());
        SmartDashboard.putData("RunShooter", new RunShooter());
        SmartDashboard.putData("LoadShooter", new LoadShooter());
        SmartDashboard.putData("ShootLow", new ShootLow());
        SmartDashboard.putData("ToggleShootingTilt", new ToggleShootingTilt());
        SmartDashboard.putData("AutoIntake", new AutoIntake());
        SmartDashboard.putData("PivotIntake", new PivotIntake());
        SmartDashboard.putData("RunIntakeIn", new RunIntakeIn());
        SmartDashboard.putData("RunIntakeOut", new RunIntakeOut());

    }

    public Joystick getLeftJoy() {
        return leftJoy;
    }

    public Joystick getRightJoy() {
        return rightJoy;
    }

    public Joystick getManipulator() {
        return manipulator;
    }


}

